#include <doctest/doctest.h>
#include <je2be.hpp>

using namespace std;

TEST_CASE("block-data") {
  static unordered_map<string, unordered_map<string, string>> const table = {
      {"minecraft:acacia_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:acacia_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:acacia_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:acacia_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:acacia_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:acacia_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:acacia_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:acacia_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:activator_rail", {{"rail_data_bit", "uint8_t"}, {"rail_direction", "int32_t"}}},
      {"minecraft:air", {}},
      {"minecraft:allow", {}},
      {"minecraft:amethyst_block", {}},
      {"minecraft:amethyst_cluster", {{"facing_direction", "int32_t"}}},
      {"minecraft:ancient_debris", {}},
      {"minecraft:andesite_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:anvil", {{"damage", "string"}, {"direction", "int32_t"}}},
      {"minecraft:azalea", {}},
      {"minecraft:azalea_leaves", {{"persistent_bit", "uint8_t"}, {"update_bit", "uint8_t"}}},
      {"minecraft:azalea_leaves_flowered", {{"persistent_bit", "uint8_t"}, {"update_bit", "uint8_t"}}},
      {"minecraft:bamboo", {{"age_bit", "uint8_t"}, {"bamboo_leaf_size", "string"}, {"bamboo_stalk_thickness", "string"}}},
      {"minecraft:bamboo_sapling", {{"age_bit", "uint8_t"}, {"sapling_type", "string"}}},
      {"minecraft:barrel", {{"facing_direction", "int32_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:barrier", {}},
      {"minecraft:basalt", {{"pillar_axis", "string"}}},
      {"minecraft:beacon", {}},
      {"minecraft:bed", {{"direction", "int32_t"}, {"head_piece_bit", "uint8_t"}, {"occupied_bit", "uint8_t"}}},
      {"minecraft:bedrock", {{"infiniburn_bit", "uint8_t"}}},
      {"minecraft:bee_nest", {{"direction", "int32_t"}, {"honey_level", "int32_t"}}},
      {"minecraft:beehive", {{"direction", "int32_t"}, {"honey_level", "int32_t"}}},
      {"minecraft:beetroot", {{"growth", "int32_t"}}},
      {"minecraft:bell", {{"attachment", "string"}, {"direction", "int32_t"}, {"toggle_bit", "uint8_t"}}},
      {"minecraft:big_dripleaf", {{"big_dripleaf_head", "uint8_t"}, {"big_dripleaf_tilt", "string"}, {"direction", "int32_t"}}},
      {"minecraft:birch_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:birch_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:birch_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:birch_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:birch_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:birch_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:birch_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:birch_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:black_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:black_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:black_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:blackstone", {}},
      {"minecraft:blackstone_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:blackstone_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:blackstone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:blackstone_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:blast_furnace", {{"facing_direction", "int32_t"}}},
      {"minecraft:blue_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:blue_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:blue_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:blue_ice", {}},
      {"minecraft:bone_block", {{"deprecated", "int32_t"}, {"pillar_axis", "string"}}},
      {"minecraft:bookshelf", {}},
      {"minecraft:border_block", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:brewing_stand", {{"brewing_stand_slot_a_bit", "uint8_t"}, {"brewing_stand_slot_b_bit", "uint8_t"}, {"brewing_stand_slot_c_bit", "uint8_t"}}},
      {"minecraft:brick_block", {}},
      {"minecraft:brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:brown_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:brown_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:brown_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:brown_mushroom", {}},
      {"minecraft:brown_mushroom_block", {{"huge_mushroom_bits", "int32_t"}}},
      {"minecraft:bubble_column", {{"drag_down", "uint8_t"}}},
      {"minecraft:budding_amethyst", {}},
      {"minecraft:cactus", {{"age", "int32_t"}}},
      {"minecraft:cake", {{"bite_counter", "int32_t"}}},
      {"minecraft:calcite", {}},
      {"minecraft:camera", {}},
      {"minecraft:campfire", {{"direction", "int32_t"}, {"extinguished", "uint8_t"}}},
      {"minecraft:candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:carpet", {{"color", "string"}}},
      {"minecraft:carrots", {{"growth", "int32_t"}}},
      {"minecraft:cartography_table", {}},
      {"minecraft:carved_pumpkin", {{"direction", "int32_t"}}},
      {"minecraft:cauldron", {{"cauldron_liquid", "string"}, {"fill_level", "int32_t"}}},
      {"minecraft:cave_vines", {{"growing_plant_age", "int32_t"}}},
      {"minecraft:cave_vines_body_with_berries", {{"growing_plant_age", "int32_t"}}},
      {"minecraft:cave_vines_head_with_berries", {{"growing_plant_age", "int32_t"}}},
      {"minecraft:chain", {{"pillar_axis", "string"}}},
      {"minecraft:chain_command_block", {{"conditional_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:chemical_heat", {}},
      {"minecraft:chemistry_table", {{"chemistry_table_type", "string"}, {"direction", "int32_t"}}},
      {"minecraft:chest", {{"facing_direction", "int32_t"}}},
      {"minecraft:chiseled_deepslate", {}},
      {"minecraft:chiseled_nether_bricks", {}},
      {"minecraft:chiseled_polished_blackstone", {}},
      {"minecraft:chorus_flower", {{"age", "int32_t"}}},
      {"minecraft:chorus_plant", {}},
      {"minecraft:clay", {}},
      {"minecraft:coal_block", {}},
      {"minecraft:coal_ore", {}},
      {"minecraft:cobbled_deepslate", {}},
      {"minecraft:cobbled_deepslate_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:cobbled_deepslate_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:cobbled_deepslate_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:cobbled_deepslate_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:cobblestone", {}},
      {"minecraft:cobblestone_wall", {{"wall_block_type", "string"}, {"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:cocoa", {{"age", "int32_t"}, {"direction", "int32_t"}}},
      {"minecraft:colored_torch_bp", {{"color_bit", "uint8_t"}, {"torch_facing_direction", "string"}}},
      {"minecraft:colored_torch_rg", {{"color_bit", "uint8_t"}, {"torch_facing_direction", "string"}}},
      {"minecraft:command_block", {{"conditional_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:composter", {{"composter_fill_level", "int32_t"}}},
      {"minecraft:concrete", {{"color", "string"}}},
      {"minecraft:concretePowder", {{"color", "string"}}},
      {"minecraft:conduit", {}},
      {"minecraft:copper_block", {}},
      {"minecraft:copper_ore", {}},
      {"minecraft:coral", {{"coral_color", "string"}, {"dead_bit", "uint8_t"}}},
      {"minecraft:coral_block", {{"coral_color", "string"}, {"dead_bit", "uint8_t"}}},
      {"minecraft:coral_fan", {{"coral_color", "string"}, {"coral_fan_direction", "int32_t"}}},
      {"minecraft:coral_fan_dead", {{"coral_color", "string"}, {"coral_fan_direction", "int32_t"}}},
      {"minecraft:coral_fan_hang", {{"coral_direction", "int32_t"}, {"coral_hang_type_bit", "uint8_t"}, {"dead_bit", "uint8_t"}}},
      {"minecraft:coral_fan_hang2", {{"coral_direction", "int32_t"}, {"coral_hang_type_bit", "uint8_t"}, {"dead_bit", "uint8_t"}}},
      {"minecraft:coral_fan_hang3", {{"coral_direction", "int32_t"}, {"coral_hang_type_bit", "uint8_t"}, {"dead_bit", "uint8_t"}}},
      {"minecraft:cracked_deepslate_bricks", {}},
      {"minecraft:cracked_deepslate_tiles", {}},
      {"minecraft:cracked_nether_bricks", {}},
      {"minecraft:cracked_polished_blackstone_bricks", {}},
      {"minecraft:crafting_table", {}},
      {"minecraft:crimson_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:crimson_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:crimson_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:crimson_fence", {}},
      {"minecraft:crimson_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:crimson_fungus", {}},
      {"minecraft:crimson_hyphae", {{"pillar_axis", "string"}}},
      {"minecraft:crimson_nylium", {}},
      {"minecraft:crimson_planks", {}},
      {"minecraft:crimson_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:crimson_roots", {}},
      {"minecraft:crimson_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:crimson_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:crimson_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:crimson_stem", {{"pillar_axis", "string"}}},
      {"minecraft:crimson_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:crimson_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:crying_obsidian", {}},
      {"minecraft:cut_copper", {}},
      {"minecraft:cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:cyan_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:cyan_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:cyan_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:dark_oak_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:dark_oak_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:dark_oak_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:dark_oak_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:dark_oak_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:dark_oak_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:dark_prismarine_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:darkoak_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:darkoak_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:daylight_detector", {{"redstone_signal", "int32_t"}}},
      {"minecraft:daylight_detector_inverted", {{"redstone_signal", "int32_t"}}},
      {"minecraft:deadbush", {}},
      {"minecraft:deepslate", {{"pillar_axis", "string"}}},
      {"minecraft:deepslate_brick_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:deepslate_brick_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:deepslate_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:deepslate_brick_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:deepslate_bricks", {}},
      {"minecraft:deepslate_coal_ore", {}},
      {"minecraft:deepslate_copper_ore", {}},
      {"minecraft:deepslate_diamond_ore", {}},
      {"minecraft:deepslate_emerald_ore", {}},
      {"minecraft:deepslate_gold_ore", {}},
      {"minecraft:deepslate_iron_ore", {}},
      {"minecraft:deepslate_lapis_ore", {}},
      {"minecraft:deepslate_redstone_ore", {}},
      {"minecraft:deepslate_tile_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:deepslate_tile_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:deepslate_tile_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:deepslate_tile_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:deepslate_tiles", {}},
      {"minecraft:deny", {}},
      {"minecraft:detector_rail", {{"rail_data_bit", "uint8_t"}, {"rail_direction", "int32_t"}}},
      {"minecraft:diamond_block", {}},
      {"minecraft:diamond_ore", {}},
      {"minecraft:diorite_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:dirt", {{"dirt_type", "string"}}},
      {"minecraft:dirt_with_roots", {}},
      {"minecraft:dispenser", {{"facing_direction", "int32_t"}, {"triggered_bit", "uint8_t"}}},
      {"minecraft:double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:double_plant", {{"double_plant_type", "string"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:double_stone_slab", {{"stone_slab_type", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:double_stone_slab2", {{"stone_slab_type_2", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:double_stone_slab3", {{"stone_slab_type_3", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:double_stone_slab4", {{"stone_slab_type_4", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:double_wooden_slab", {{"top_slot_bit", "uint8_t"}, {"wood_type", "string"}}},
      {"minecraft:dragon_egg", {}},
      {"minecraft:dried_kelp_block", {}},
      {"minecraft:dripstone_block", {}},
      {"minecraft:dropper", {{"facing_direction", "int32_t"}, {"triggered_bit", "uint8_t"}}},
      {"minecraft:emerald_block", {}},
      {"minecraft:emerald_ore", {}},
      {"minecraft:enchanting_table", {}},
      {"minecraft:end_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:end_bricks", {}},
      {"minecraft:end_gateway", {}},
      {"minecraft:end_portal", {}},
      {"minecraft:end_portal_frame", {{"direction", "int32_t"}, {"end_portal_eye_bit", "uint8_t"}}},
      {"minecraft:end_rod", {{"facing_direction", "int32_t"}}},
      {"minecraft:end_stone", {}},
      {"minecraft:ender_chest", {{"facing_direction", "int32_t"}}},
      {"minecraft:exposed_copper", {}},
      {"minecraft:exposed_cut_copper", {}},
      {"minecraft:exposed_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:exposed_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:exposed_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:farmland", {{"moisturized_amount", "int32_t"}}},
      {"minecraft:fence", {{"wood_type", "string"}}},
      {"minecraft:fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:fire", {{"age", "int32_t"}}},
      {"minecraft:fletching_table", {}},
      {"minecraft:flower_pot", {{"update_bit", "uint8_t"}}},
      {"minecraft:flowering_azalea", {}},
      {"minecraft:flowing_lava", {{"liquid_depth", "int32_t"}}},
      {"minecraft:flowing_water", {{"liquid_depth", "int32_t"}}},
      {"minecraft:frame", {{"facing_direction", "int32_t"}, {"item_frame_map_bit", "uint8_t"}}},
      {"minecraft:frosted_ice", {{"age", "int32_t"}}},
      {"minecraft:furnace", {{"facing_direction", "int32_t"}}},
      {"minecraft:gilded_blackstone", {}},
      {"minecraft:glass", {}},
      {"minecraft:glass_pane", {}},
      {"minecraft:glow_frame", {{"facing_direction", "int32_t"}, {"item_frame_map_bit", "uint8_t"}}},
      {"minecraft:glow_lichen", {{"multi_face_direction_bits", "int32_t"}}},
      {"minecraft:glowingobsidian", {}},
      {"minecraft:glowstone", {}},
      {"minecraft:gold_block", {}},
      {"minecraft:gold_ore", {}},
      {"minecraft:golden_rail", {{"rail_data_bit", "uint8_t"}, {"rail_direction", "int32_t"}}},
      {"minecraft:granite_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:grass", {}},
      {"minecraft:grass_path", {}},
      {"minecraft:gravel", {}},
      {"minecraft:gray_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:gray_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:gray_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:green_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:green_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:green_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:grindstone", {{"attachment", "string"}, {"direction", "int32_t"}}},
      {"minecraft:hanging_roots", {}},
      {"minecraft:hard_glass", {}},
      {"minecraft:hard_glass_pane", {}},
      {"minecraft:hard_stained_glass", {{"color", "string"}}},
      {"minecraft:hard_stained_glass_pane", {{"color", "string"}}},
      {"minecraft:hardened_clay", {}},
      {"minecraft:hay_block", {{"deprecated", "int32_t"}, {"pillar_axis", "string"}}},
      {"minecraft:heavy_weighted_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:honey_block", {}},
      {"minecraft:honeycomb_block", {}},
      {"minecraft:hopper", {{"facing_direction", "int32_t"}, {"toggle_bit", "uint8_t"}}},
      {"minecraft:ice", {}},
      {"minecraft:infested_deepslate", {{"pillar_axis", "string"}}},
      {"minecraft:info_update", {}},
      {"minecraft:info_update2", {}},
      {"minecraft:invisibleBedrock", {}},
      {"minecraft:iron_bars", {}},
      {"minecraft:iron_block", {}},
      {"minecraft:iron_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:iron_ore", {}},
      {"minecraft:iron_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      //{"minecraft:jigsaw", {{"facing_direction", "int32_t"}, {"rotation", "int32_t"}}},
      {"minecraft:jukebox", {}},
      {"minecraft:jungle_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:jungle_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:jungle_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:jungle_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:jungle_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:jungle_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:jungle_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:jungle_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:kelp", {{"kelp_age", "int32_t"}}},
      {"minecraft:ladder", {{"facing_direction", "int32_t"}}},
      {"minecraft:lantern", {{"hanging", "uint8_t"}}},
      {"minecraft:lapis_block", {}},
      {"minecraft:lapis_ore", {}},
      {"minecraft:large_amethyst_bud", {{"facing_direction", "int32_t"}}},
      {"minecraft:lava", {{"liquid_depth", "int32_t"}}},
      {"minecraft:lava_cauldron", {{"cauldron_liquid", "string"}, {"fill_level", "int32_t"}}},
      {"minecraft:leaves", {{"old_leaf_type", "string"}, {"persistent_bit", "uint8_t"}, {"update_bit", "uint8_t"}}},
      {"minecraft:leaves2", {{"new_leaf_type", "string"}, {"persistent_bit", "uint8_t"}, {"update_bit", "uint8_t"}}},
      {"minecraft:lectern", {{"direction", "int32_t"}, {"powered_bit", "uint8_t"}}},
      {"minecraft:lever", {{"lever_direction", "string"}, {"open_bit", "uint8_t"}}},
      {"minecraft:light_block", {{"block_light_level", "int32_t"}}},
      {"minecraft:light_blue_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:light_blue_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:light_blue_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:light_gray_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:light_gray_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:light_weighted_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:lightning_rod", {{"facing_direction", "int32_t"}}},
      {"minecraft:lime_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:lime_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:lime_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:lit_blast_furnace", {{"facing_direction", "int32_t"}}},
      {"minecraft:lit_deepslate_redstone_ore", {}},
      {"minecraft:lit_furnace", {{"facing_direction", "int32_t"}}},
      {"minecraft:lit_pumpkin", {{"direction", "int32_t"}}},
      {"minecraft:lit_redstone_lamp", {}},
      {"minecraft:lit_redstone_ore", {}},
      {"minecraft:lit_smoker", {{"facing_direction", "int32_t"}}},
      {"minecraft:lodestone", {}},
      {"minecraft:log", {{"old_log_type", "string"}, {"pillar_axis", "string"}}},
      {"minecraft:log2", {{"new_log_type", "string"}, {"pillar_axis", "string"}}},
      {"minecraft:loom", {{"direction", "int32_t"}}},
      {"minecraft:magenta_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:magenta_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:magenta_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:magma", {}},
      {"minecraft:medium_amethyst_bud", {{"facing_direction", "int32_t"}}},
      {"minecraft:melon_block", {}},
      {"minecraft:melon_stem", {{"facing_direction", "int32_t"}, {"growth", "int32_t"}}},
      //{"minecraft:mob_spawner", {}},
      {"minecraft:monster_egg", {{"monster_egg_stone_type", "string"}}},
      {"minecraft:moss_block", {}},
      {"minecraft:moss_carpet", {}},
      {"minecraft:mossy_cobblestone", {}},
      {"minecraft:mossy_cobblestone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:mossy_stone_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:movingBlock", {}},
      {"minecraft:mycelium", {}},
      {"minecraft:nether_brick", {}},
      {"minecraft:nether_brick_fence", {}},
      {"minecraft:nether_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:nether_gold_ore", {}},
      {"minecraft:nether_sprouts", {}},
      {"minecraft:nether_wart", {{"age", "int32_t"}}},
      {"minecraft:nether_wart_block", {}},
      {"minecraft:netherite_block", {}},
      {"minecraft:netherrack", {}},
      {"minecraft:netherreactor", {}},
      {"minecraft:normal_stone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:noteblock", {}},
      {"minecraft:oak_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:observer", {{"facing_direction", "int32_t"}, {"powered_bit", "uint8_t"}}},
      {"minecraft:obsidian", {}},
      {"minecraft:orange_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:orange_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:orange_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:oxidized_copper", {}},
      {"minecraft:oxidized_cut_copper", {}},
      {"minecraft:oxidized_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:oxidized_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:oxidized_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:packed_ice", {}},
      {"minecraft:pink_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:pink_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:pink_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:piston", {{"facing_direction", "int32_t"}}},
      {"minecraft:pistonArmCollision", {{"facing_direction", "int32_t"}}},
      {"minecraft:planks", {{"wood_type", "string"}}},
      {"minecraft:podzol", {}},
      {"minecraft:pointed_dripstone", {{"dripstone_thickness", "string"}, {"hanging", "uint8_t"}}},
      {"minecraft:polished_andesite_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:polished_basalt", {{"pillar_axis", "string"}}},
      {"minecraft:polished_blackstone", {}},
      {"minecraft:polished_blackstone_brick_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:polished_blackstone_brick_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:polished_blackstone_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:polished_blackstone_brick_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:polished_blackstone_bricks", {}},
      {"minecraft:polished_blackstone_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:polished_blackstone_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:polished_blackstone_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:polished_blackstone_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:polished_blackstone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:polished_blackstone_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:polished_deepslate", {}},
      {"minecraft:polished_deepslate_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:polished_deepslate_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:polished_deepslate_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:polished_deepslate_wall", {{"wall_connection_type_east", "string"}, {"wall_connection_type_north", "string"}, {"wall_connection_type_south", "string"}, {"wall_connection_type_west", "string"}, {"wall_post_bit", "uint8_t"}}},
      {"minecraft:polished_diorite_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:polished_granite_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:portal", {{"portal_axis", "string"}}},
      {"minecraft:potatoes", {{"growth", "int32_t"}}},
      {"minecraft:powder_snow", {}},
      {"minecraft:powered_comparator", {{"direction", "int32_t"}, {"output_lit_bit", "uint8_t"}, {"output_subtract_bit", "uint8_t"}}},
      {"minecraft:powered_repeater", {{"direction", "int32_t"}, {"repeater_delay", "int32_t"}}},
      {"minecraft:prismarine", {{"prismarine_block_type", "string"}}},
      {"minecraft:prismarine_bricks_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:prismarine_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:pumpkin", {{"direction", "int32_t"}}},
      {"minecraft:pumpkin_stem", {{"facing_direction", "int32_t"}, {"growth", "int32_t"}}},
      {"minecraft:purple_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:purple_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:purple_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:purpur_block", {{"chisel_type", "string"}, {"pillar_axis", "string"}}},
      {"minecraft:purpur_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:quartz_block", {{"chisel_type", "string"}, {"pillar_axis", "string"}}},
      {"minecraft:quartz_bricks", {}},
      {"minecraft:quartz_ore", {}},
      {"minecraft:quartz_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:rail", {{"rail_direction", "int32_t"}}},
      {"minecraft:raw_copper_block", {}},
      {"minecraft:raw_gold_block", {}},
      {"minecraft:raw_iron_block", {}},
      {"minecraft:red_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:red_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:red_flower", {{"flower_type", "string"}}},
      {"minecraft:red_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:red_mushroom", {}},
      {"minecraft:red_mushroom_block", {{"huge_mushroom_bits", "int32_t"}}},
      {"minecraft:red_nether_brick", {}},
      {"minecraft:red_nether_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:red_sandstone", {{"sand_stone_type", "string"}}},
      {"minecraft:red_sandstone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:redstone_block", {}},
      {"minecraft:redstone_lamp", {}},
      {"minecraft:redstone_ore", {}},
      {"minecraft:redstone_torch", {{"torch_facing_direction", "string"}}},
      {"minecraft:redstone_wire", {{"redstone_signal", "int32_t"}}},
      {"minecraft:reeds", {{"age", "int32_t"}}},
      {"minecraft:repeating_command_block", {{"conditional_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:reserved6", {}},
      {"minecraft:respawn_anchor", {{"respawn_anchor_charge", "int32_t"}}},
      {"minecraft:sand", {{"sand_type", "string"}}},
      {"minecraft:sandstone", {{"sand_stone_type", "string"}}},
      {"minecraft:sandstone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:sapling", {{"age_bit", "uint8_t"}, {"sapling_type", "string"}}},
      {"minecraft:scaffolding", {{"stability", "int32_t"}, {"stability_check", "uint8_t"}}},
      {"minecraft:sculk_sensor", {{"powered_bit", "uint8_t"}}},
      {"minecraft:seaLantern", {}},
      {"minecraft:sea_pickle", {{"cluster_count", "int32_t"}, {"dead_bit", "uint8_t"}}},
      {"minecraft:seagrass", {{"sea_grass_type", "string"}}},
      {"minecraft:shroomlight", {}},
      {"minecraft:shulker_box", {{"color", "string"}}},
      {"minecraft:silver_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:skull", {{"facing_direction", "int32_t"}, {"no_drop_bit", "uint8_t"}}},
      {"minecraft:slime", {}},
      {"minecraft:small_amethyst_bud", {{"facing_direction", "int32_t"}}},
      {"minecraft:small_dripleaf_block", {{"direction", "int32_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:smithing_table", {}},
      {"minecraft:smoker", {{"facing_direction", "int32_t"}}},
      {"minecraft:smooth_basalt", {}},
      {"minecraft:smooth_quartz_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:smooth_red_sandstone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:smooth_sandstone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:smooth_stone", {}},
      {"minecraft:snow", {}},
      {"minecraft:snow_layer", {{"covered_bit", "uint8_t"}, {"height", "int32_t"}}},
      {"minecraft:soul_campfire", {{"direction", "int32_t"}, {"extinguished", "uint8_t"}}},
      {"minecraft:soul_fire", {{"age", "int32_t"}}},
      {"minecraft:soul_lantern", {{"hanging", "uint8_t"}}},
      {"minecraft:soul_sand", {}},
      {"minecraft:soul_soil", {}},
      {"minecraft:soul_torch", {{"torch_facing_direction", "string"}}},
      {"minecraft:sponge", {{"sponge_type", "string"}}},
      {"minecraft:spore_blossom", {}},
      {"minecraft:spruce_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:spruce_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:spruce_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:spruce_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:spruce_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:spruce_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:spruce_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:spruce_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:stained_glass", {{"color", "string"}}},
      {"minecraft:stained_glass_pane", {{"color", "string"}}},
      {"minecraft:stained_hardened_clay", {{"color", "string"}}},
      {"minecraft:standing_banner", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:stickyPistonArmCollision", {{"facing_direction", "int32_t"}}},
      {"minecraft:sticky_piston", {{"facing_direction", "int32_t"}}},
      {"minecraft:stone", {{"stone_type", "string"}}},
      {"minecraft:stone_brick_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:stone_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:stone_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:stone_slab", {{"stone_slab_type", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:stone_slab2", {{"stone_slab_type_2", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:stone_slab3", {{"stone_slab_type_3", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:stone_slab4", {{"stone_slab_type_4", "string"}, {"top_slot_bit", "uint8_t"}}},
      {"minecraft:stone_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:stonebrick", {{"stone_brick_type", "string"}}},
      {"minecraft:stonecutter", {}},
      {"minecraft:stonecutter_block", {{"facing_direction", "int32_t"}}},
      {"minecraft:stripped_acacia_log", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_birch_log", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_crimson_hyphae", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_crimson_stem", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_dark_oak_log", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_jungle_log", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_oak_log", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_spruce_log", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_warped_hyphae", {{"pillar_axis", "string"}}},
      {"minecraft:stripped_warped_stem", {{"pillar_axis", "string"}}},
      {"minecraft:structure_block", {{"structure_block_type", "string"}}},
      {"minecraft:structure_void", {{"structure_void_type", "string"}}},
      {"minecraft:sweet_berry_bush", {{"growth", "int32_t"}}},
      {"minecraft:tallgrass", {{"tall_grass_type", "string"}}},
      {"minecraft:target", {}},
      {"minecraft:tinted_glass", {}},
      {"minecraft:tnt", {{"allow_underwater_bit", "uint8_t"}, {"explode_bit", "uint8_t"}}},
      {"minecraft:torch", {{"torch_facing_direction", "string"}}},
      {"minecraft:trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:trapped_chest", {{"facing_direction", "int32_t"}}},
      {"minecraft:tripWire", {{"attached_bit", "uint8_t"}, {"disarmed_bit", "uint8_t"}, {"powered_bit", "uint8_t"}, {"suspended_bit", "uint8_t"}}},
      {"minecraft:tripwire_hook", {{"attached_bit", "uint8_t"}, {"direction", "int32_t"}, {"powered_bit", "uint8_t"}}},
      {"minecraft:tuff", {}},
      {"minecraft:turtle_egg", {{"cracked_state", "string"}, {"turtle_egg_count", "string"}}},
      {"minecraft:twisting_vines", {{"twisting_vines_age", "int32_t"}}},
      {"minecraft:underwater_torch", {{"torch_facing_direction", "string"}}},
      {"minecraft:undyed_shulker_box", {}},
      {"minecraft:unknown", {}},
      {"minecraft:unlit_redstone_torch", {{"torch_facing_direction", "string"}}},
      {"minecraft:unpowered_comparator", {{"direction", "int32_t"}, {"output_lit_bit", "uint8_t"}, {"output_subtract_bit", "uint8_t"}}},
      {"minecraft:unpowered_repeater", {{"direction", "int32_t"}, {"repeater_delay", "int32_t"}}},
      {"minecraft:vine", {{"vine_direction_bits", "int32_t"}}},
      {"minecraft:wall_banner", {{"facing_direction", "int32_t"}}},
      {"minecraft:wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:warped_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:warped_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:warped_double_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:warped_fence", {}},
      {"minecraft:warped_fence_gate", {{"direction", "int32_t"}, {"in_wall_bit", "uint8_t"}, {"open_bit", "uint8_t"}}},
      {"minecraft:warped_fungus", {}},
      {"minecraft:warped_hyphae", {{"pillar_axis", "string"}}},
      {"minecraft:warped_nylium", {}},
      {"minecraft:warped_planks", {}},
      {"minecraft:warped_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:warped_roots", {}},
      {"minecraft:warped_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:warped_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:warped_standing_sign", {{"ground_sign_direction", "int32_t"}}},
      {"minecraft:warped_stem", {{"pillar_axis", "string"}}},
      {"minecraft:warped_trapdoor", {{"direction", "int32_t"}, {"open_bit", "uint8_t"}, {"upside_down_bit", "uint8_t"}}},
      {"minecraft:warped_wall_sign", {{"facing_direction", "int32_t"}}},
      {"minecraft:warped_wart_block", {}},
      {"minecraft:water", {{"liquid_depth", "int32_t"}}},
      {"minecraft:waterlily", {}},
      {"minecraft:waxed_copper", {}},
      {"minecraft:waxed_cut_copper", {}},
      {"minecraft:waxed_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:waxed_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_exposed_copper", {}},
      {"minecraft:waxed_exposed_cut_copper", {}},
      {"minecraft:waxed_exposed_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_exposed_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:waxed_exposed_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_oxidized_copper", {}},
      {"minecraft:waxed_oxidized_cut_copper", {}},
      {"minecraft:waxed_oxidized_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_oxidized_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:waxed_oxidized_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_weathered_copper", {}},
      {"minecraft:waxed_weathered_cut_copper", {}},
      {"minecraft:waxed_weathered_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:waxed_weathered_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:waxed_weathered_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:weathered_copper", {}},
      {"minecraft:weathered_cut_copper", {}},
      {"minecraft:weathered_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:weathered_cut_copper_stairs", {{"upside_down_bit", "uint8_t"}, {"weirdo_direction", "int32_t"}}},
      {"minecraft:weathered_double_cut_copper_slab", {{"top_slot_bit", "uint8_t"}}},
      {"minecraft:web", {}},
      {"minecraft:weeping_vines", {{"weeping_vines_age", "int32_t"}}},
      {"minecraft:wheat", {{"growth", "int32_t"}}},
      {"minecraft:white_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:white_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:white_glazed_terracotta", {{"facing_direction", "int32_t"}}},
      {"minecraft:wither_rose", {}},
      {"minecraft:wood", {{"pillar_axis", "string"}, {"stripped_bit", "uint8_t"}, {"wood_type", "string"}}},
      {"minecraft:wooden_button", {{"button_pressed_bit", "uint8_t"}, {"facing_direction", "int32_t"}}},
      {"minecraft:wooden_door", {{"direction", "int32_t"}, {"door_hinge_bit", "uint8_t"}, {"open_bit", "uint8_t"}, {"upper_block_bit", "uint8_t"}}},
      {"minecraft:wooden_pressure_plate", {{"redstone_signal", "int32_t"}}},
      {"minecraft:wooden_slab", {{"top_slot_bit", "uint8_t"}, {"wood_type", "string"}}},
      {"minecraft:wool", {{"color", "string"}}},
      {"minecraft:yellow_candle", {{"candles", "int32_t"}, {"lit", "uint8_t"}}},
      {"minecraft:yellow_candle_cake", {{"lit", "uint8_t"}}},
      {"minecraft:yellow_flower", {}},
      {"minecraft:yellow_glazed_terracotta", {{"facing_direction", "int32_t"}}},

      {"minecraft:tripwire", {{"attached_bit", "bool"}, {"disarmed_bit", "bool"}, {"powered_bit", "bool"}, {"suspended_bit", "bool"}}},
  };

  for (mcfile::blocks::BlockId id = 1; id < mcfile::blocks::minecraft::minecraft_max_block_id; id++) {
    string blockName = mcfile::blocks::Name(id);
    CHECK(!blockName.empty());
    auto block = make_shared<mcfile::Block const>(blockName);
    shared_ptr<mcfile::nbt::CompoundTag> converted = j2b::BlockData::From(block);
    CHECK(converted != nullptr);
    if (!converted) {
      continue;
    }

    auto bedrockBlockName = converted->string("name");
    CHECK(bedrockBlockName);
    if (!bedrockBlockName) {
      continue;
    }

    auto found = table.find(*bedrockBlockName);
    CHECK(found != table.end());

    auto states = converted->compoundTag("states");
    unordered_set<string> keysInStates;
    if (states) {
      for (auto it : *states) {
        keysInStates.insert(it.first);
      }
    }

    auto const &props = found->second;

    if (keysInStates.size() == props.size()) {
      for (auto it : props) {
        keysInStates.erase(it.first);
      }
      CHECK(keysInStates.empty());
    } else {
      for (auto it : keysInStates) {
        CHECK(props.find(it) != props.end());
      }
      for (auto it : props) {
        CHECK(keysInStates.find(it.first) != keysInStates.end());
      }
    }

    for (auto j = props.begin(); j != props.end(); j++) {
      string name = j->first;
      string type = j->second;
      CHECK(states != nullptr);
      if (states == nullptr) {
        continue;
      }
      shared_ptr<mcfile::nbt::Tag> p = (*states)[name];
      CHECK(p != nullptr);
      if (!p) {
        continue;
      }
      if (type == "uint8_t" || type == "bool") {
        CHECK(p->asByte() != nullptr);
      } else if (type == "int32_t") {
        CHECK(p->asInt() != nullptr);
      } else if (type == "string") {
        CHECK(p->asString() != nullptr);
      } else {
        CHECK(false);
      }
    }
  }
}
