#!/bin/bash

(
	cd "$(dirname "$0")/.."

	if clang-format --version | grep 'version 12.' >/dev/null; then
		bash tool/ls-files | xargs -P$(nproc) -n1 clang-format -i
	else
		docker run --rm -v$(pwd):/workspace -w /workspace je2be-clang-format bash -c "bash tool/ls-files | xargs -P$(nproc) -n1 clang-format -i"
		bash tool/ls-files | xargs chmod 644
	fi
)
