#pragma once

#include <minecraft-file.hpp>

#include "terraform/_block-accessor.hpp"
#include "terraform/_block-property-accessor.hpp"

namespace je2be::toje {

class Lighting {
public:
  static void Do(mcfile::je::Chunk &out, terraform::BlockAccessor<mcfile::je::Block> &blockAccessor, terraform::BlockPropertyAccessor const &propertyAccessor) {
    int x = out.minBlockX();
    int y = -64;
    int z = out.minBlockZ();

    // TODO:
  }

private:
  static int LightAttenuationAmountById(mcfile::blocks::BlockId id) {
    using namespace mcfile::blocks::minecraft;
    switch (id) {
    case acacia_button:
    case acacia_door:
    case acacia_fence:
    case acacia_fence_gate:
    case acacia_pressure_plate:
    case acacia_sapling:
    case acacia_sign:
    case acacia_trapdoor:
    case acacia_wall_sign:
    case activator_rail:
    case air:
    case allium:
    case andesite_wall:
    case anvil:
    case attached_melon_stem:
    case attached_pumpkin_stem:
    case azure_bluet:
    case bamboo_sapling:
    case barrier:
    case beetroots:
    case bell:
    case birch_button:
    case birch_door:
    case birch_fence:
    case birch_fence_gate:
    case birch_pressure_plate:
    case birch_sapling:
    case birch_sign:
    case birch_trapdoor:
    case birch_wall_sign:
    case black_banner:
    case black_bed:
    case black_carpet:
    case black_stained_glass:
    case black_stained_glass_pane:
    case black_wall_banner:
    case blue_banner:
    case blue_bed:
    case blue_carpet:
    case blue_orchid:
    case blue_stained_glass:
    case blue_stained_glass_pane:
    case blue_wall_banner:
    case brewing_stand:
    case brick_wall:
    case brown_banner:
    case brown_bed:
    case brown_carpet:
    case brown_mushroom:
    case brown_stained_glass:
    case brown_stained_glass_pane:
    case brown_wall_banner:
    case cactus:
    case cake:
    case campfire:
    case carrots:
    case cauldron:
    case cave_air:
    case chest:
    case chipped_anvil:
    case cobblestone_wall:
    case cocoa:
    case composter:
    case cornflower:
    case creeper_head:
    case creeper_wall_head:
    case cyan_banner:
    case cyan_bed:
    case cyan_carpet:
    case cyan_stained_glass:
    case cyan_stained_glass_pane:
    case cyan_wall_banner:
    case damaged_anvil:
    case dandelion:
    case dark_oak_button:
    case dark_oak_door:
    case dark_oak_fence:
    case dark_oak_fence_gate:
    case dark_oak_pressure_plate:
    case dark_oak_sapling:
    case dark_oak_sign:
    case dark_oak_trapdoor:
    case dark_oak_wall_sign:
    case daylight_detector:
    case dead_bush:
    case detector_rail:
    case diorite_wall:
    case dragon_egg:
    case dragon_head:
    case dragon_wall_head:
    case enchanting_table:
    case end_portal:
    case end_portal_frame:
    case end_rod:
    case end_stone_brick_wall:
    case ender_chest:
    case farmland:
    case fern:
    case fire:
    case flower_pot:
    case glass:
    case glass_pane:
    case granite_wall:
    case grass:
    case gray_banner:
    case gray_bed:
    case gray_carpet:
    case gray_stained_glass:
    case gray_stained_glass_pane:
    case gray_wall_banner:
    case green_banner:
    case green_bed:
    case green_carpet:
    case green_stained_glass:
    case green_stained_glass_pane:
    case green_wall_banner:
    case grindstone:
    case heavy_weighted_pressure_plate:
    case hopper:
    case iron_bars:
    case iron_door:
    case iron_trapdoor:
    case jungle_button:
    case jungle_door:
    case jungle_fence:
    case jungle_fence_gate:
    case jungle_pressure_plate:
    case jungle_sapling:
    case jungle_sign:
    case jungle_trapdoor:
    case jungle_wall_sign:
    case ladder:
    case lantern:
    case large_fern:
    case lectern:
    case lever:
    case light_blue_banner:
    case light_blue_bed:
    case light_blue_carpet:
    case light_blue_stained_glass:
    case light_blue_stained_glass_pane:
    case light_blue_wall_banner:
    case light_gray_banner:
    case light_gray_bed:
    case light_gray_carpet:
    case light_gray_stained_glass:
    case light_gray_stained_glass_pane:
    case light_gray_wall_banner:
    case light_weighted_pressure_plate:
    case lilac:
    case lily_of_the_valley:
    case lily_pad:
    case lime_banner:
    case lime_bed:
    case lime_carpet:
    case lime_stained_glass:
    case lime_stained_glass_pane:
    case lime_wall_banner:
    case magenta_banner:
    case magenta_bed:
    case magenta_carpet:
    case magenta_stained_glass:
    case magenta_stained_glass_pane:
    case magenta_wall_banner:
    case melon_stem:
    case mossy_cobblestone_wall:
    case mossy_stone_brick_wall:
    case moving_piston:
    case nether_brick_fence:
    case nether_brick_wall:
    case nether_portal:
    case nether_wart:
    case oak_button:
    case oak_door:
    case oak_fence:
    case oak_fence_gate:
    case oak_pressure_plate:
    case oak_sapling:
    case oak_sign:
    case oak_trapdoor:
    case oak_wall_sign:
    case orange_banner:
    case orange_bed:
    case orange_carpet:
    case orange_stained_glass:
    case orange_stained_glass_pane:
    case orange_tulip:
    case orange_wall_banner:
    case oxeye_daisy:
    case peony:
    case pink_banner:
    case pink_bed:
    case pink_carpet:
    case pink_stained_glass:
    case pink_stained_glass_pane:
    case pink_tulip:
    case pink_wall_banner:
    case piston_head:
    case player_head:
    case player_wall_head:
    case poppy:
    case potatoes:
    case potted_acacia_sapling:
    case potted_allium:
    case potted_azure_bluet:
    case potted_bamboo:
    case potted_birch_sapling:
    case potted_blue_orchid:
    case potted_brown_mushroom:
    case potted_cactus:
    case potted_cornflower:
    case potted_dandelion:
    case potted_dark_oak_sapling:
    case potted_dead_bush:
    case potted_fern:
    case potted_jungle_sapling:
    case potted_lily_of_the_valley:
    case potted_oak_sapling:
    case potted_orange_tulip:
    case potted_oxeye_daisy:
    case potted_pink_tulip:
    case potted_poppy:
    case potted_red_mushroom:
    case potted_red_tulip:
    case potted_spruce_sapling:
    case potted_white_tulip:
    case potted_wither_rose:
    case powered_rail:
    case prismarine_wall:
    case pumpkin_stem:
    case purple_banner:
    case purple_bed:
    case purple_carpet:
    case purple_stained_glass:
    case purple_stained_glass_pane:
    case purple_wall_banner:
    case rail:
    case red_banner:
    case red_bed:
    case red_carpet:
    case red_mushroom:
    case red_nether_brick_wall:
    case red_sandstone_wall:
    case red_stained_glass:
    case red_stained_glass_pane:
    case red_tulip:
    case red_wall_banner:
    case comparator:
    case redstone_wire:
    case repeater:
    case redstone_torch:
    case redstone_wall_torch:
    case rose_bush:
    case sandstone_wall:
    case scaffolding:
    case skeleton_skull:
    case skeleton_wall_skull:
    case snow:
    case spruce_button:
    case spruce_door:
    case spruce_fence:
    case spruce_fence_gate:
    case spruce_pressure_plate:
    case spruce_sapling:
    case spruce_sign:
    case spruce_trapdoor:
    case spruce_wall_sign:
    case stone_brick_wall:
    case stone_button:
    case stone_pressure_plate:
    case stonecutter:
    case structure_void:
    case sugar_cane:
    case sunflower:
    case sweet_berry_bush:
    case tall_grass:
    case torch:
    case trapped_chest:
    case tripwire:
    case tripwire_hook:
    case turtle_egg:
    case vine:
    case void_air:
    case wall_torch:
    case wheat:
    case white_banner:
    case white_bed:
    case white_carpet:
    case white_stained_glass:
    case white_stained_glass_pane:
    case white_tulip:
    case white_wall_banner:
    case wither_rose:
    case wither_skeleton_skull:
    case wither_skeleton_wall_skull:
    case yellow_banner:
    case yellow_bed:
    case yellow_carpet:
    case yellow_stained_glass:
    case yellow_stained_glass_pane:
    case yellow_wall_banner:
    case zombie_head:
    case zombie_wall_head:
    case crimson_fungus:
    case warped_fungus:
    case crimson_roots:
    case warped_roots:
    case nether_sprouts:
    case weeping_vines:
    case twisting_vines:
    case crimson_fence:
    case warped_fence:
    case soul_torch:
    case chain:
    case blackstone_wall:
    case polished_blackstone_wall:
    case polished_blackstone_brick_wall:
    case soul_lantern:
    case soul_campfire:
    case crimson_pressure_plate:
    case warped_pressure_plate:
    case crimson_trapdoor:
    case warped_trapdoor:
    case crimson_fence_gate:
    case warped_fence_gate:
    case crimson_button:
    case warped_button:
    case crimson_door:
    case warped_door:
    case crimson_sign:
    case warped_sign:
    case polished_blackstone_pressure_plate:
    case polished_blackstone_button:
    case crimson_wall_sign:
    case warped_wall_sign:
    case soul_wall_torch:
    case azalea:
    case flowering_azalea:
    case spore_blossom:
    case moss_carpet:
    case hanging_roots:
    case potted_azalea_bush:
    case potted_flowering_azalea_bush:
    case water_cauldron:
    case lava_cauldron:
    case powder_snow_cauldron:
    case dirt_path:
    case big_dripleaf:
    case big_dripleaf_stem:
    case small_dripleaf:
    case candle:
    case white_candle:
    case orange_candle:
    case magenta_candle:
    case light_blue_candle:
    case yellow_candle:
    case lime_candle:
    case pink_candle:
    case gray_candle:
    case light_gray_candle:
    case cyan_candle:
    case purple_candle:
    case blue_candle:
    case brown_candle:
    case green_candle:
    case red_candle:
    case black_candle:
    case candle_cake:
    case white_candle_cake:
    case orange_candle_cake:
    case magenta_candle_cake:
    case light_blue_candle_cake:
    case yellow_candle_cake:
    case lime_candle_cake:
    case pink_candle_cake:
    case gray_candle_cake:
    case light_gray_candle_cake:
    case cyan_candle_cake:
    case purple_candle_cake:
    case blue_candle_cake:
    case brown_candle_cake:
    case green_candle_cake:
    case red_candle_cake:
    case black_candle_cake:
    case cobbled_deepslate_wall:
    case polished_deepslate_wall:
    case deepslate_brick_wall:
    case deepslate_tile_wall:
    case lightning_rod:
    case small_amethyst_bud:
    case medium_amethyst_bud:
    case large_amethyst_bud:
    case amethyst_cluster:
    case pointed_dripstone:
    case light:
    case cave_vines:
    case glow_lichen:
    case potted_crimson_fungus:
    case potted_warped_fungus:
    case potted_crimson_roots:
    case potted_warped_roots:
    case sculk_sensor:
    case mangrove_fence:
    case mangrove_fence_gate:
    case mud_brick_wall:
    case mangrove_sign:
    case mangrove_wall_sign:
    case mangrove_propagule:
    case mangrove_button:
    case mangrove_pressure_plate:
    case mangrove_door:
    case mangrove_trapdoor:
    case frogspawn:
    case potted_mangrove_propagule:
    case acacia_hanging_sign:
    case acacia_wall_hanging_sign:
    case bamboo_button:
    case bamboo_door:
    case bamboo_fence:
    case bamboo_fence_gate:
    case bamboo_hanging_sign:
    case bamboo_pressure_plate:
    case bamboo_sign:
    case bamboo_trapdoor:
    case bamboo_wall_hanging_sign:
    case bamboo_wall_sign:
    case birch_hanging_sign:
    case birch_wall_hanging_sign:
    case crimson_hanging_sign:
    case crimson_wall_hanging_sign:
    case dark_oak_hanging_sign:
    case dark_oak_wall_hanging_sign:
    case jungle_hanging_sign:
    case jungle_wall_hanging_sign:
    case mangrove_hanging_sign:
    case mangrove_wall_hanging_sign:
    case oak_hanging_sign:
    case oak_wall_hanging_sign:
    case piglin_head:
    case piglin_wall_head:
    case spruce_hanging_sign:
    case spruce_wall_hanging_sign:
    case warped_hanging_sign:
    case warped_wall_hanging_sign:
      return 0;
    case acacia_leaves:
    case beacon:
    case birch_leaves:
    case black_shulker_box:
    case blue_shulker_box:
    case brain_coral:
    case brain_coral_fan:
    case brain_coral_wall_fan:
    case brown_shulker_box:
    case bubble_column:
    case bubble_coral:
    case bubble_coral_fan:
    case bubble_coral_wall_fan:
    case chorus_flower:
    case chorus_plant:
    case cobweb:
    case conduit:
    case cyan_shulker_box:
    case dark_oak_leaves:
    case dead_brain_coral:
    case dead_brain_coral_fan:
    case dead_brain_coral_wall_fan:
    case dead_bubble_coral:
    case dead_bubble_coral_fan:
    case dead_bubble_coral_wall_fan:
    case dead_fire_coral:
    case dead_fire_coral_fan:
    case dead_fire_coral_wall_fan:
    case dead_horn_coral:
    case dead_horn_coral_fan:
    case dead_horn_coral_wall_fan:
    case dead_tube_coral:
    case dead_tube_coral_fan:
    case dead_tube_coral_wall_fan:
    case end_gateway:
    case fire_coral:
    case fire_coral_fan:
    case fire_coral_wall_fan:
    case frosted_ice:
    case gray_shulker_box:
    case green_shulker_box:
    case horn_coral:
    case horn_coral_fan:
    case horn_coral_wall_fan:
    case ice:
    case jungle_leaves:
    case kelp:
    case lava:
    case light_blue_shulker_box:
    case light_gray_shulker_box:
    case lime_shulker_box:
    case magenta_shulker_box:
    case oak_leaves:
    case orange_shulker_box:
    case pink_shulker_box:
    case purple_shulker_box:
    case red_shulker_box:
    case sea_pickle:
    case seagrass:
    case shulker_box:
    case slime_block:
    case spawner:
    case spruce_leaves:
    case tall_seagrass:
    case tube_coral:
    case tube_coral_fan:
    case tube_coral_wall_fan:
    case water:
    case white_shulker_box:
    case yellow_shulker_box:
    case honey_block:
    case azalea_leaves:
    case powder_snow:
    case flowering_azalea_leaves:
    case sculk_shrieker:
    case sculk_vein:
    case mangrove_roots:
    case mangrove_leaves:
      return 1;
    case acacia_log:
    case acacia_planks:
    case acacia_wood:
    case andesite:
    case barrel:
    case bedrock:
    case birch_log:
    case birch_planks:
    case birch_wood:
    case black_concrete:
    case black_concrete_powder:
    case black_glazed_terracotta:
    case black_terracotta:
    case black_wool:
    case blast_furnace:
    case coal_block:
    case diamond_block:
    case emerald_block:
    case gold_block:
    case iron_block:
    case quartz_block:
    case redstone_block:
    case blue_concrete:
    case blue_concrete_powder:
    case blue_glazed_terracotta:
    case blue_ice:
    case blue_terracotta:
    case blue_wool:
    case bone_block:
    case bookshelf:
    case brain_coral_block:
    case bricks:
    case brown_concrete:
    case brown_concrete_powder:
    case brown_glazed_terracotta:
    case brown_mushroom_block:
    case brown_terracotta:
    case brown_wool:
    case bubble_coral_block:
    case cartography_table:
    case carved_pumpkin:
    case chain_command_block:
    case chiseled_quartz_block:
    case chiseled_red_sandstone:
    case chiseled_sandstone:
    case chiseled_stone_bricks:
    case clay:
    case coal_ore:
    case coarse_dirt:
    case cobblestone:
    case command_block:
    case cracked_stone_bricks:
    case crafting_table:
    case cut_red_sandstone:
    case cut_sandstone:
    case cyan_concrete:
    case cyan_concrete_powder:
    case cyan_glazed_terracotta:
    case cyan_terracotta:
    case cyan_wool:
    case dark_oak_log:
    case dark_oak_planks:
    case dark_oak_wood:
    case dark_prismarine:
    case dead_brain_coral_block:
    case dead_bubble_coral_block:
    case dead_fire_coral_block:
    case dead_horn_coral_block:
    case dead_tube_coral_block:
    case diamond_ore:
    case diorite:
    case dirt:
    case dispenser:
    case dried_kelp_block:
    case dropper:
    case emerald_ore:
    case end_stone:
    case end_stone_bricks:
    case fire_coral_block:
    case fletching_table:
    case furnace:
    case glowstone:
    case gold_ore:
    case granite:
    case grass_block:
    case gravel:
    case gray_concrete:
    case gray_concrete_powder:
    case gray_glazed_terracotta:
    case gray_terracotta:
    case gray_wool:
    case green_concrete:
    case green_concrete_powder:
    case green_glazed_terracotta:
    case green_terracotta:
    case green_wool:
    case hay_block:
    case horn_coral_block:
    case infested_chiseled_stone_bricks:
    case infested_cobblestone:
    case infested_cracked_stone_bricks:
    case infested_mossy_stone_bricks:
    case infested_stone:
    case infested_stone_bricks:
    case iron_ore:
    case jack_o_lantern:
    case jigsaw:
    case jukebox:
    case jungle_log:
    case jungle_planks:
    case jungle_wood:
    case lapis_block:
    case lapis_ore:
    case light_blue_concrete:
    case light_blue_concrete_powder:
    case light_blue_glazed_terracotta:
    case light_blue_terracotta:
    case light_blue_wool:
    case light_gray_concrete:
    case light_gray_concrete_powder:
    case light_gray_glazed_terracotta:
    case light_gray_terracotta:
    case light_gray_wool:
    case lime_concrete:
    case lime_concrete_powder:
    case lime_glazed_terracotta:
    case lime_terracotta:
    case lime_wool:
    case loom:
    case magenta_concrete:
    case magenta_concrete_powder:
    case magenta_glazed_terracotta:
    case magenta_terracotta:
    case magenta_wool:
    case magma_block:
    case melon:
    case mossy_cobblestone:
    case mossy_stone_bricks:
    case mushroom_stem:
    case mycelium:
    case nether_bricks:
    case nether_quartz_ore:
    case nether_wart_block:
    case netherrack:
    case note_block:
    case oak_log:
    case oak_planks:
    case oak_wood:
    case observer:
    case obsidian:
    case orange_concrete:
    case orange_concrete_powder:
    case orange_glazed_terracotta:
    case orange_terracotta:
    case orange_wool:
    case packed_ice:
    case pink_concrete:
    case pink_concrete_powder:
    case pink_glazed_terracotta:
    case pink_terracotta:
    case pink_wool:
    case piston:
    case podzol:
    case polished_andesite:
    case polished_diorite:
    case polished_granite:
    case prismarine:
    case prismarine_bricks:
    case pumpkin:
    case purple_concrete:
    case purple_concrete_powder:
    case purple_glazed_terracotta:
    case purple_terracotta:
    case purple_wool:
    case purpur_block:
    case purpur_pillar:
    case quartz_pillar:
    case red_concrete:
    case red_concrete_powder:
    case red_glazed_terracotta:
    case red_mushroom_block:
    case red_nether_bricks:
    case red_sand:
    case red_sandstone:
    case red_terracotta:
    case red_wool:
    case redstone_lamp:
    case redstone_ore:
    case repeating_command_block:
    case sand:
    case sandstone:
    case sea_lantern:
    case smithing_table:
    case smoker:
    case smooth_quartz:
    case smooth_red_sandstone:
    case smooth_sandstone:
    case smooth_stone:
    case snow_block:
    case soul_sand:
    case sponge:
    case spruce_log:
    case spruce_planks:
    case spruce_wood:
    case sticky_piston:
    case stone:
    case stone_bricks:
    case stripped_acacia_log:
    case stripped_acacia_wood:
    case stripped_birch_log:
    case stripped_birch_wood:
    case stripped_dark_oak_log:
    case stripped_dark_oak_wood:
    case stripped_jungle_log:
    case stripped_jungle_wood:
    case stripped_oak_log:
    case stripped_oak_wood:
    case stripped_spruce_log:
    case stripped_spruce_wood:
    case structure_block:
    case terracotta:
    case tnt:
    case tube_coral_block:
    case wet_sponge:
    case white_concrete:
    case white_concrete_powder:
    case white_glazed_terracotta:
    case white_terracotta:
    case white_wool:
    case yellow_concrete:
    case yellow_concrete_powder:
    case yellow_glazed_terracotta:
    case yellow_terracotta:
    case yellow_wool:
    case bee_nest:
    case beehive:
    case honeycomb_block:
    case crimson_nylium:
    case warped_nylium:
    case crimson_planks:
    case warped_planks:
    case nether_gold_ore:
    case crimson_stem:
    case warped_stem:
    case stripped_crimson_stem:
    case stripped_warped_stem:
    case crimson_hyphae:
    case warped_hyphae:
    case cracked_nether_bricks:
    case chiseled_nether_bricks:
    case netherite_block:
    case soul_soil:
    case basalt:
    case polished_basalt:
    case ancient_debris:
    case crying_obsidian:
    case blackstone:
    case gilded_blackstone:
    case polished_blackstone:
    case chiseled_polished_blackstone:
    case polished_blackstone_bricks:
    case cracked_polished_blackstone_bricks:
    case shroomlight:
    case lodestone:
    case respawn_anchor:
    case target:
    case warped_wart_block:
    case quartz_bricks:
    case stripped_crimson_hyphae:
    case stripped_warped_hyphae:
    case deepslate:
    case cobbled_deepslate:
    case polished_deepslate:
    case calcite:
    case tuff:
    case dripstone_block:
    case deepslate_coal_ore:
    case deepslate_iron_ore:
    case copper_ore:
    case deepslate_copper_ore:
    case deepslate_gold_ore:
    case deepslate_redstone_ore:
    case deepslate_emerald_ore:
    case deepslate_lapis_ore:
    case deepslate_diamond_ore:
    case raw_iron_block:
    case raw_copper_block:
    case raw_gold_block:
    case amethyst_block:
    case budding_amethyst:
    case copper_block:
    case exposed_copper:
    case weathered_copper:
    case oxidized_copper:
    case cut_copper:
    case exposed_cut_copper:
    case weathered_cut_copper:
    case oxidized_cut_copper:
    case waxed_copper_block:
    case waxed_exposed_copper:
    case waxed_weathered_copper:
    case waxed_oxidized_copper:
    case waxed_cut_copper:
    case waxed_exposed_cut_copper:
    case waxed_weathered_cut_copper:
    case waxed_oxidized_cut_copper:
    case tinted_glass:
    case moss_block:
    case infested_deepslate:
    case deepslate_bricks:
    case cracked_deepslate_bricks:
    case deepslate_tiles:
    case cracked_deepslate_tiles:
    case chiseled_deepslate:
    case smooth_basalt:
    case rooted_dirt:
    case reinforced_deepslate:
    case sculk:
    case sculk_catalyst:
    case mangrove_planks:
    case muddy_mangrove_roots:
    case mangrove_log:
    case stripped_mangrove_log:
    case stripped_mangrove_wood:
    case mangrove_wood:
    case packed_mud:
    case mud_bricks:
    case ochre_froglight:
    case verdant_froglight:
    case pearlescent_froglight:
    case mud:
    case bamboo_block:
    case bamboo_mosaic:
    case bamboo_planks:
    case chiseled_bookshelf:
    case stripped_bamboo_block:
      return 15;
    default:
      return 0;
    }
  }
};

} // namespace je2be::toje
